---
title: "Tensorflow in R"
author: "Prof. Dr. Jan Kirenz"
date: "10 12 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(keras)
```

```{r}
mnist <- dataset_mnist()

mnist$train$x <- mnist$train$x/255
mnist$test$x <- mnist$test$x/255
```

```{r}
model <- keras_model_sequential() %>% 
  layer_flatten(input_shape = c(28, 28)) %>% 
  layer_dense(units = 128, activation = "relu") %>% 
  layer_dropout(0.2) %>% 
  layer_dense(10, activation = "softmax")
```

```{r}
summary(model)
```

```{r}
model %>% 
  compile(
    loss = "sparse_categorical_crossentropy",
    optimizer = "adam",
    metrics = "accuracy"
  )
```

```{r}
model %>% 
  fit(
    x = mnist$train$x, y = mnist$train$y,
    epochs = 5,
    validation_split = 0.3,
    verbose = 2
  )
```


```{r}
predictions <- predict(model, mnist$test$x)
head(predictions, 2)
```


```{r}
model %>% 
  evaluate(mnist$test$x, mnist$test$y, verbose = 0)
```


```{r}
save_model_tf(object = model, filepath = "model")
```

```{r}
# reloaded_model <- load_model_tf("model")
# all.equal(predict(model, mnist$test$x), predict(reloaded_model, mnist$test$x))
```

